<?php
use EfTech\ContactList;
/**
 * @var ContactList\Service\SearchAddressService\AddressDto[] $Addresses;
 * @var ContactList\Service\SearchContactsService\ContactDto[] $contacts
 * @var array $formValidationResults
 * @var array $addressData
 */
?>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Hello, Address!</title>
</head>

<table class="table table-striped" style="width: 600px; margin: auto;">
    <thead>
    <tr>
        <th> № </th>
        <th> id Контакта </th>
        <th> Адрес </th>
        <th> Статус </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($Addresses as $index => $Address): ?>
        <tr>
            <td><?php print $index ?> </td>
            <td> <?php foreach ($contacts as $contact): ?>
                    <?php   if($contact->getIdRecipient() === $Address->getIdRecipient()): ?>
                        <?php print $contact->getFullName() . ' ' . $Address->getIdRecipient() ?>
                    <?php endif; ?>

                <?php endforeach; ?>
            </td>
            <td>
                <?php print $Address->getAddress() ?>
            </td>
            <td>
                <?php print $Address->getStatus() ?>
            </td>
        </tr>
    <?php endforeach; ?>

    </tbody>
</table>

<div class="mb-3" style="margin: auto; width: 300px">
    <h2>Добавить адрес</h2>
    <form method="post">
        <div>
            <label for="address_id_recipient" class="form-label" >Информация о контакте</label>
            <select name="id_recipient" id="address_id_recipient" class="form-select" aria-label="Default select example" style="width: 300px" >
                <?php foreach ($contacts as $index => $contact): ?>
                    <option <?php echo (isset($addressData['id_recipient'])
                    && $addressData['id_recipient']
                    === (string)$contact->getIdRecipient() ? 'selected' : '') ?> value="<?php echo $contact->getIdRecipient() ?>">
                        <?php echo $contact->getFullName() ?>
                        <?php echo $contact->getIdRecipient() ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label for="address" class="form-label">Адрес</label>
            <input style="width: 300px"  class="form-control" type="text" name="address" id="address" value="<?php echo ($addressData['address'] ?? '') ?>">
            <?php if (isset($formValidationResults['address']['address'])): ?>
                <ul>
                    <?php foreach ($formValidationResults['address']['address'] as $err): ?>
                        <li><?php print $err ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
        <div>
            <label for="status_address" class="form-label">Статус</label>
            <select name="status" id="status_address" class="form-select" aria-label="Default select example" style="width: 300px">
                <option value="Home">Home</option>
                <option value="Work">Work</option>
            </select>
        </div>
        <div>
            <input type="submit" value="Добавить" class="btn btn-primary"/>
        </div>
    </form>
</div>







<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

