
<h1>
    Аутентификация
</h1>

<div>
    <form method="post">
        <div>
            <label for="login">Логин</label>
            <input type="text" name="login" id="login">
        </div>
        <div>
            <label for="password">Пароль</label>
            <input type="password" name="password" id="password">
        </div>
        <div>
            <input type="submit" name="submit" value="Войти">
        </div>
    </form>
</div>
<?php if (isset($errMsg)): ?>
    <?php echo $errMsg ?>
<?php endif; ?>
